name: Deploy github page

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github_page"
  cancel-in-progress: true

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install -w textarea-handling

      - name: Build
        run: npm run build -w textarea-handling

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: workspaces/textarea-handling/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
